# Generated by Django 5.0.7 on 2024-11-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
