# Generated by Django 5.0.7 on 2024-12-02 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_catfoodcart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=600)),
                ('image', models.ImageField(default='', upload_to='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.catgory')),
            ],
            options={
                'db_table': 'CatHealth',
            },
        ),
        migrations.CreateModel(
            name='CatHealthCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathealth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.cathealth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
