# Generated by Django 5.0.7 on 2024-12-02 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_cattoys_cattoyscart_dogfood_dogfoodcart_doghealth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kittencarecart',
            name='kittencare',
        ),
        migrations.RemoveField(
            model_name='kittencarecart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kittentoys',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kittentoyscart',
            name='kittentoys',
        ),
        migrations.RemoveField(
            model_name='kittentoyscart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='puppycare',
            name='category',
        ),
        migrations.RemoveField(
            model_name='puppycarecart',
            name='puppycare',
        ),
        migrations.RemoveField(
            model_name='puppycarecart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='puppytoys',
            name='category',
        ),
        migrations.RemoveField(
            model_name='puppytoyscart',
            name='puppytoys',
        ),
        migrations.RemoveField(
            model_name='puppytoyscart',
            name='user',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.DeleteModel(
            name='KittenCare',
        ),
        migrations.DeleteModel(
            name='KittenCareCart',
        ),
        migrations.DeleteModel(
            name='KittenToys',
        ),
        migrations.DeleteModel(
            name='KittenToysCart',
        ),
        migrations.DeleteModel(
            name='PuppyCare',
        ),
        migrations.DeleteModel(
            name='PuppyCareCart',
        ),
        migrations.DeleteModel(
            name='PuppyToys',
        ),
        migrations.DeleteModel(
            name='PuppyToysCart',
        ),
    ]
